debug-message: false
firstrun: true
database:
  #PLEASE ENSURE ALL VALUES ARE ACCURATE!!
  enabled: false
  ip: 127.0.0.0
  port: 36606
  name: mc07
  username: user
  password: pass
payperiod: 1h
managers: false