name: BusinessCore
version: 1.0.0-Alpha
author: Desireaux
main: me.beastman3226.bc.BusinessCore
depend: [Vault, PlaceholderAPI]
commands:
  business:
    description: Commands for controlling business operations
    permission: businesscore.business
    usage: "/business [start|<close>|<withdraw>|<deposit>|<balance>|<info>|<list>|employee] [<arguments>]"
  job:
    description: Commands for accessing jobs
    permission: businesscore.job
    usage: "/job [open|claim|list|complete|current|info|tp] [<arguments>]"