name: BusinessCore
version: 0.0.1
author: beastman3226
main: me.beastman3226.bc.Main
depend: [Vault]
commands:
  b.create:
    description: Creates a business
    usage: "Try b.create [name]"
    permission: business.create
    permission-message: "&4You do not have 'business.create' or the like, please talk to an adminstrator"
    aliases: [business.create, create, b.c]
  b.delete:
    description: Delete your business, or (from console) someone elses
    usage: "Try b.delete (or from console: b.delete [player_name|business_id]"
    permission: business.delete
    permission-message: "&4You do not have 'business.delete' or the like, please talk to an adminstrator"
    aliases: [business.delete, delete, b.d]
  b.withdraw:
    description: Withdraws money from your business
    usage: "/<command> [amount], if the amount is greater than the balance you will error out."
    permission: business.withdraw
    permission-message: "&4You do not have 'business.withdraw' or the like, please talk to an adminstrator"
    aliases: [business.withdraw, withdraw, b.w]
  b.deposit:
    description:
permissions:
  business.business:
    description: Gives permission to business side
    default: true
  business.admin:
    description: Allows player to use admin commands
    default: op
  business.owner.delete:
    description: Gives permission to delete own business
    default: false